name: nawy_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.7.0
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.0.1
  path_provider: ^2.1.5
  path: ^1.8.3
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  injectable: ^2.5.1
  get_it: ^8.2.0
  logger: ^2.4.0
  mocktail: ^1.0.4
  rxdart: ^0.28.0
  bloc: ^9.0.0
  material_symbols_icons: ^4.2785.1
  cached_network_image: ^3.4.1
  firebase_core: ^4.1.0
  firebase_ai: ^3.2.0
  flutter_chat_ui: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.6.0
  injectable_generator: ^2.4.2
  analyzer: ^7.7.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - properties.json