// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgz2J-xuxc8DHSxJ4D_SkownlBdoxTqLA',
    appId: '1:485173601243:web:e10e7e2a73e24f72ef7dfe',
    messagingSenderId: '485173601243',
    projectId: 'nawy-7ee29',
    authDomain: 'nawy-7ee29.firebaseapp.com',
    storageBucket: 'nawy-7ee29.firebasestorage.app',
    measurementId: 'G-ZT2FKLRVB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATv-gN84MiNRctHzgHTK7dEGZdoDlHJ4I',
    appId: '1:485173601243:android:c5aac0f4dd8ec05cef7dfe',
    messagingSenderId: '485173601243',
    projectId: 'nawy-7ee29',
    storageBucket: 'nawy-7ee29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Q3xwhBxPVdz29jTDHlar6yoKcYO9zOM',
    appId: '1:485173601243:ios:9e0cec5ed95addebef7dfe',
    messagingSenderId: '485173601243',
    projectId: 'nawy-7ee29',
    storageBucket: 'nawy-7ee29.firebasestorage.app',
    iosBundleId: 'com.example.nawyApp',
  );

}